// Original synthetic fixture writer based on Apple's published QuickTime atom specification.
// Synthetic codec pixels/sound are generated by CI, no private photograph is used.
import {boxes,children,child,concat} from '../../src/media/bytes';
const text=(s:string)=>new TextEncoder().encode(s);
function nums(...values:number[]):Uint8Array{const b=new Uint8Array(values.length*4);values.forEach((v,i)=>new DataView(b.buffer).setUint32(i*4,v));return b;}
function atom(type:string|number,payload:Uint8Array):Uint8Array{const b=concat(nums(payload.length+8),typeof type==='string'?text(type):nums(type),payload);return b;}
function table(type:string,...values:number[]):Uint8Array{return atom(type,nums(0,...values));}
const id='01234567-89AB-CDEF-0123-456789ABCDEF';
export function appleFixture(photo:Uint8Array,movie:Uint8Array):{photo:Uint8Array;movie:Uint8Array}{
  const maker=new Uint8Array(32+id.length+1),m=new DataView(maker.buffer);
  maker.set(text('Apple iOS\0'));maker.set([0,1,77,77],10);m.setUint16(14,1);m.setUint16(16,17);m.setUint16(18,2);m.setUint32(20,id.length+1);m.setUint32(24,32);maker.set(text(id),32);
  const tiff=new Uint8Array(44+maker.length),t=new DataView(tiff.buffer);tiff.set([73,73]);t.setUint16(2,42,true);t.setUint32(4,8,true);
  t.setUint16(8,1,true);t.setUint16(10,0x8769,true);t.setUint16(12,4,true);t.setUint32(14,1,true);t.setUint32(18,26,true);
  t.setUint16(26,1,true);t.setUint16(28,0x927c,true);t.setUint16(30,7,true);t.setUint32(32,maker.length,true);t.setUint32(36,44,true);tiff.set(maker,44);
  const exif=concat(text('Exif\0\0'),tiff),segment=new Uint8Array(exif.length+4);segment.set([255,225]);new DataView(segment.buffer).setUint16(2,exif.length+2);segment.set(exif,4);
  const outputPhoto=concat(photo.slice(0,2),segment,photo.slice(2));
  const top=boxes(movie),moov=top.find(b=>b.type==='moov')!,baseTrack=children(movie,moov).find(b=>b.type==='trak')!;
  const tkhdBox=child(movie,baseTrack,'tkhd'),tkhd=movie.slice(tkhdBox.start,tkhdBox.end);new DataView(tkhd.buffer).setUint32(20,3);tkhd.fill(0,tkhd.length-8);
  const mdhd=new Uint8Array(24);new DataView(mdhd.buffer).setUint32(12,1000);new DataView(mdhd.buffer).setUint32(16,1000);
  const declaration=atom('keyd',concat(text('mdta'),text('com.apple.quicktime.still-image-time')));
  const key=atom(1,concat(declaration,atom('dtyp',nums(0,65))));
  const sample=atom(1,new Uint8Array([255]));
  const entry=atom('mebx',concat(new Uint8Array([0,0,0,0,0,0,0,1]),atom('keys',key)));
  const stbl=atom('stbl',concat(atom('stsd',concat(nums(0,1),entry)),table('stts',1,1,1000),table('stsc',1,1,1,1),table('stsz',sample.length,1),table('stco',1,movie.length+8)));
  const handler=atom('hdlr',concat(nums(0,0),text('meta'),nums(0,0,0),text('Timed metadata\0')));
  const dinf=atom('dinf',atom('dref',concat(nums(0,1),atom('url ',nums(1)))));
  const gmhd=atom('gmhd',atom('gmin',new Uint8Array(16)));
  const trak=atom('trak',concat(tkhd,atom('mdia',concat(atom('mdhd',mdhd),handler,atom('minf',concat(gmhd,dinf,stbl))))));
  const contentKey=text('com.apple.quicktime.content.identifier');
  const keys=atom('keys',concat(nums(0,1,8+contentKey.length),text('mdta'),contentKey));
  const ilst=atom('ilst',atom(1,atom('data',concat(nums(1,0),text(id)))));
  const metadata=atom('meta',concat(nums(0),atom('hdlr',concat(nums(0,0),text('mdta'),nums(0,0,0),new Uint8Array([0]))),keys,ilst));
  const expanded=atom('moov',concat(...children(movie,moov).map(c=>movie.slice(c.start,c.end)),trak,metadata));
  const original=movie.slice();original.set(text('free'),moov.start+4);
  return {photo:outputPhoto,movie:concat(original,atom('mdat',sample),expanded)};
}
