// SPDX-License-Identifier: GPL-3.0-only
import {TFile, type App} from 'obsidian';
import {sourceReferences, mergeReferences, type Reference, type ReferenceProvider, type Rule} from './source';
import type {Config} from '../settings/model';
export class ReferenceIndex {
  providers = new Map<string, ReferenceProvider>();
  constructor(private app: App, private settings: () => Config) {}
  register(provider: ReferenceProvider): () => void {
    if(provider.version!==1||!/^[-\w]{1,64}$/.test(provider.id)||this.providers.has(provider.id))throw new Error('Provider identity/version rejected');
    this.providers.set(provider.id,provider);
    return ()=>{if(this.providers.get(provider.id)===provider){this.providers.delete(provider.id);provider.dispose?.();}};
  }
  resolve(ref: Reference): Reference {
    if(/^(https?:|data:|blob:|file:|app:)/i.test(ref.link))return {...ref,evidence:'unresolved',reason:'Remote or rendered URL needs verified source identity'};
    let link=ref.link;
    try{link=decodeURIComponent(link);}catch{return {...ref,evidence:'unresolved',reason:'Malformed encoded path'};}
    const file=this.app.metadataCache.getFirstLinkpathDest(link,ref.source);
    if(!(file instanceof TFile))return {...ref,evidence:'unresolved',reason:'Missing target'};
    return {...ref,path:file.path};
  }
  async note(file: TFile, signal: AbortSignal): Promise<Reference[]> {
    const c=this.settings(),text=await this.app.vault.cachedRead(file);
    const refs=sourceReferences(text,file.path,{native:!!c['detect.native'],html:!!c['detect.html'],codeCandidates:!!c['detect.codeCandidates'],rules:c['detect.rules'] as unknown as Rule[],legacyLive:!!c['compatibility.legacyLive']});
    const metadata=this.app.metadataCache.getFileCache(file);
    if(c['detect.native'])for(const embed of metadata?.embeds??[])refs.push({link:embed.link,source:file.path,evidence:'direct',origin:'metadata-cache',offset:embed.position.start.offset});
    for(const field of c['detect.frontmatterFields'] as string[]){const v=metadata?.frontmatter?.[field];if(typeof v==='string')refs.push({link:v.replace(/^!\[\[|\]\]$/g,''),source:file.path,evidence:'candidate',origin:'frontmatter:'+field,offset:0});}
    const switches=c['detect.providers'] as Record<string,unknown>;
    for(const provider of this.providers.values())if(switches[provider.id]!==false){
      if(signal.aborted)throw new Error('Cancelled');
      try{const values=await Promise.race([provider.references(file.path,signal),new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('Provider timeout')),3000))]);
        for(const value of values.slice(0,10000))if(value.source===file.path&&typeof value.link==='string'&&['direct','dynamic','candidate','unresolved'].includes(value.evidence))refs.push(value);
      }catch{/* provider failure cannot abort other references */}
    }
    return mergeReferences(refs.map(ref=>this.resolve(ref)));
  }
  rendered(img: HTMLImageElement, source: string): Reference {
    const url=img.currentSrc||img.src;
    // Resource URLs generated by the public Vault API, not basename guessing.
    for(const file of this.app.vault.getFiles())if(this.app.vault.getResourcePath(file)===url || this.app.vault.getResourcePath(file).split('?')[0]===url.split('?')[0])
      return {source,link:file.path,path:file.path,evidence:'dynamic',origin:'rendered',offset:0};
    return {source,link:'',evidence:'unresolved',origin:'rendered',offset:0,reason:'Rendered media has no verified original'};
  }
  eligible(file: TFile): boolean {
    const c=this.settings(),p=file.path;
    if(p.split('/').some(s=>s.startsWith('.'))||p.startsWith(String(c['storage.backupDirectory'])+'/')||p.startsWith(String(c['storage.reportDirectory'])+'/'))return false;
    if(!(c['scope.extensions'] as string[]).map(v=>v.toLowerCase()).includes(file.extension.toLowerCase()))return false;
    const within=(root:string)=>p===root||p.startsWith(root+'/');
    const includes=c['scope.includeFolders'] as string[],excludes=c['scope.excludeFolders'] as string[];
    return (!includes.length||includes.some(within))&&!excludes.some(within);
  }
  destroy(): void {for(const p of this.providers.values())p.dispose?.();this.providers.clear();}
}
